
import type { Video, Category } from './types';

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Epic Animation Showdown',
    description: 'A thrilling compilation of the most intense fight scenes in modern animation. Features clips from various top-rated series and films.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['action', 'fight-scene', 'sakuga'],
    categoryIds: ['cat-1', 'cat-3'],
    dataAiHint: 'animation battle',
  },
  {
    id: '2',
    title: 'Fluid Motion & FX',
    description: 'Explore the art of fluid dynamics and special effects animation. A visual treat for aspiring animators and enthusiasts.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['fx-animation', 'water', 'elemental'],
    categoryIds: ['cat-2'],
    dataAiHint: 'animation effects',
  },
  {
    id: '3',
    title: 'Character Acting & Emotion',
    description: 'A deep dive into subtle character acting. See how animators convey powerful emotions through nuanced movements.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['character-acting', 'emotion', 'subtlety'],
    categoryIds: ['cat-1', 'cat-4'],
    dataAiHint: 'emotional character',
  },
  {
    id: '4',
    title: 'Creature Animation Showcase',
    description: 'From mythical beasts to alien lifeforms, this video showcases the best in creature and animal animation.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['creature', 'monster', 'animal-locomotion'],
    categoryIds: ['cat-5'],
    dataAiHint: 'animated monster',
  },
  {
    id: '5',
    title: 'Dynamic Camera Work',
    description: 'Learn how dynamic camera movements can elevate an animation sequence. A collection of scenes with impressive cinematography.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['cinematography', 'camera-work', 'layout'],
    categoryIds: ['cat-3'],
    dataAiHint: 'dynamic perspective',
  },
  {
    id: '6',
    title: 'Short Film: "The Last Spark"',
    description: 'An award-winning short film about a small robot\'s journey to save its creator. A masterclass in storytelling.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['storytelling', 'sci-fi', 'robot'],
    categories: ['sci-fi', 'drama'],
    isShort: true,
    dataAiHint: 'robot journey',
  },
  {
    id: '7',
    title: 'Short Film: "Aquarella"',
    description: 'A beautiful, abstract short film where watercolor paintings come to life, telling a story of love and loss.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['abstract', 'watercolor', 'experimental'],
    categories: ['experimental', 'romance'],
    isShort: true,
    dataAiHint: 'watercolor painting',
  },
   {
    id: '8',
    title: 'Mecha & Robotics',
    description: 'A showcase of giant robots and intricate mechanical animations that define the mecha genre.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['mecha', 'robot', 'sci-fi'],
    categoryIds: ['cat-5', 'cat-3'],
    dataAiHint: 'giant robot',
  },
  {
    id: '9',
    title: 'Walk & Run Cycles',
    description: 'A fundamental reference for animators, this video breaks down various styles of walk and run cycles.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['walk-cycle', 'run-cycle', 'fundamentals'],
    categoryIds: ['cat-1'],
    dataAiHint: 'running animation',
  },
  {
    id: '10',
    title: 'Explosions & Debris',
    description: 'Feel the impact. A collection of the most satisfying and well-animated explosion sequences.',
    thumbnailUrl: 'https://placehold.co/1280x720.png',
    posterUrl: 'https://placehold.co/400x600.png',
    videoUrl: 'https://www.youtube.com/watch?v=Sc1Pci1T1sI',
    tags: ['explosion', 'fx-animation', 'impact'],
    categoryIds: ['cat-2'],
    dataAiHint: 'cartoon explosion',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    title: 'Character Locomotion',
    description: 'The art of character movement, from simple walks to complex parkour.',
    tags: ['2D', '3D', 'Fundamentals'],
    href: '/browse/cat-1',
    imageUrl: 'https://placehold.co/400x300.png',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    hint: 'character running',
    status: 'published',
  },
  {
    id: 'cat-2',
    title: 'Elemental FX',
    description: 'Fire, water, smoke, and magical effects that bring worlds to life.',
    tags: ['FX', '2D'],
    href: '/browse/cat-2',
    imageUrl: 'https://placehold.co/400x300.png',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    hint: 'elemental magic',
    status: 'published',
  },
  {
    id: 'cat-3',
    title: 'Action & Fight Scenes',
    description: 'High-impact combat and dynamic action sequences from top animators.',
    tags: ['Sakuga', 'Choreography'],
    href: '/browse/cat-3',
    imageUrl: 'https://placehold.co/400x300.png',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    hint: 'anime fight',
    status: 'published',
  },
  {
    id: 'cat-4',
    title: 'Character Acting',
    description: 'Subtle performances that convey deep emotion and personality.',
    tags: ['Performance', 'Dialogue'],
    href: '/browse/cat-4',
    imageUrl: 'https://placehold.co/400x300.png',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    hint: 'emotional animation',
    status: 'published',
  },
  {
    id: 'cat-5',
    title: 'Creature & Animal',
    description: 'Animating the movement and behavior of non-human characters.',
    tags: ['Quadruped', 'Flying'],
    href: '/browse/cat-5',
    imageUrl: 'https://placehold.co/400x300.png',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    hint: 'animated dragon',
    status: 'published',
  },
];
